CREATE TABLE IF NOT EXISTS account
(
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE SEQUENCE account_seq
    START WITH 1
    INCREMENT BY 50
    MINVALUE 0
    MAXVALUE 999999999
    CYCLE;